import type { ConsentRecord } from '../types/job-payload.types';
import type { ServiceCategory } from '../config/service-guardrails';
export interface OutputValidationResult { passed:boolean; autoCorrections:string[]; hardFailures:string[]; requiresRegeneration:boolean; correctedOutput?:string }
export class OutputValidator {
private readonly guaranteedResultsTerms=['guaranteed','permanent results','will definitely','you will look','cures','treats','fixes permanently','100% effective','zero risk','completely safe','no side effects','pain free guaranteed'];
private readonly medicalClaimTerms=['treats','cures','heals','medical grade results','clinically proven','FDA approved','TGA approved','dermatologist strength','prescribed'];
private readonly bodyShameTerms=['ugly','fat','overweight','fix your','hide your','disguise your','problem areas','flaws','imperfections you hate'];
async validate(caption:string,consentRecord:ConsentRecord,serviceCategory:ServiceCategory,tenantId:string):Promise<OutputValidationResult>{void serviceCategory;void tenantId;const autoCorrections:string[]=[];const hardFailures:string[]=[];let corrected=caption;for(const t of this.guaranteedResultsTerms){if(corrected.toLowerCase().includes(t))hardFailures.push(`Prohibited guaranteed-results language detected: "${t}"`);}for(const t of this.medicalClaimTerms){if(corrected.toLowerCase().includes(t))hardFailures.push(`Medical claim language detected: "${t}"`);}for(const t of this.bodyShameTerms){if(corrected.toLowerCase().includes(t))hardFailures.push(`Body-shaming language detected: "${t}"`);}if(!consentRecord.restrictions.use_name){const matches=corrected.match(/\b[A-Z][a-z]+\b/g)||[];const suspicious=matches.filter((w)=>!this.isCommonWord(w));if(suspicious.length>0)hardFailures.push(`Possible client name in content where name consent is not granted: ${suspicious.join(', ')}`);}if(corrected.length>2200){corrected=corrected.substring(0,2200)+'...';autoCorrections.push('Caption trimmed to Instagram character limit');}return{passed:hardFailures.length===0,autoCorrections,hardFailures,requiresRegeneration:hardFailures.length>0,correctedOutput:autoCorrections.length>0?corrected:undefined};}
private isCommonWord(word:string):boolean{const common=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday','January','February','March','April','May','June','July','August','September','October','November','December','Instagram','Facebook','TikTok','Studio','Salon','Growth','Beauty','Hair','Skin','Nail'];return common.includes(word);}
}
