import type { ConsentRecord } from '../types/job-payload.types';
import type { ServiceCategory } from '../config/service-guardrails';
import { MEDICAL_OUTCOME_TERMS, MEDICAL_URGENCY_TERMS } from '../config/medical-claim-terms';
export interface OutputValidationResult { passed:boolean; autoCorrections:string[]; hardFailures:string[]; requiresRegeneration:boolean; correctedOutput?:string }
export class OutputValidator {
private readonly guaranteedResultsTerms=['guaranteed','permanent results','will definitely','you will look','cures','treats','fixes permanently','100% effective','zero risk','completely safe','no side effects','pain free guaranteed'];
private readonly medicalClaimTerms=['treats','cures','heals','medical grade results','clinically proven','FDA approved','TGA approved','dermatologist strength','prescribed'];
private readonly bodyShameTerms=['ugly','fat','overweight','fix your','hide your','disguise your','problem areas','flaws','imperfections you hate'];
// Phase 4 (BRAND_DNA_GUIDED_V2 — /brand_dna_implementation_plan.md §7): additional
// terms hard-failed ONLY for medical-aesthetics practitioners — AHPRA forbids
// outcome claims and urgency/scarcity tactics that are otherwise fine for a
// regular beauty business. Enforced here in code so it cannot depend on the
// model "remembering" a sentence in the prompt.
async validate(caption:string,consentRecord:ConsentRecord,serviceCategory:ServiceCategory,tenantId:string,isMedicalPractitioner:boolean=false):Promise<OutputValidationResult>{void serviceCategory;void tenantId;const autoCorrections:string[]=[];const hardFailures:string[]=[];let corrected=caption;for(const t of this.guaranteedResultsTerms){if(corrected.toLowerCase().includes(t))hardFailures.push(`Prohibited guaranteed-results language detected: "${t}"`);}for(const t of this.medicalClaimTerms){if(corrected.toLowerCase().includes(t))hardFailures.push(`Medical claim language detected: "${t}"`);}for(const t of this.bodyShameTerms){if(corrected.toLowerCase().includes(t))hardFailures.push(`Body-shaming language detected: "${t}"`);}if(isMedicalPractitioner){for(const t of MEDICAL_OUTCOME_TERMS){if(corrected.toLowerCase().includes(t))hardFailures.push(`AHPRA: treatment-outcome claim detected: "${t}"`);}for(const t of MEDICAL_URGENCY_TERMS){if(corrected.toLowerCase().includes(t))hardFailures.push(`AHPRA: urgency/scarcity tactic detected: "${t}"`);}}if(!(consentRecord.restrictions?.use_name ?? consentRecord.allowUseName ?? true)){const matches=corrected.match(/\b[A-Z][a-z]+\b/g)||[];const suspicious=matches.filter((w)=>!this.isCommonWord(w));if(suspicious.length>0)hardFailures.push(`Possible client name in content where name consent is not granted: ${suspicious.join(', ')}`);}if(corrected.length>2200){corrected=corrected.substring(0,2200)+'...';autoCorrections.push('Caption trimmed to Instagram character limit');}return{passed:hardFailures.length===0,autoCorrections,hardFailures,requiresRegeneration:hardFailures.length>0,correctedOutput:autoCorrections.length>0?corrected:undefined};}
private isCommonWord(word:string):boolean{const common=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday','January','February','March','April','May','June','July','August','September','October','November','December','Instagram','Facebook','TikTok','Studio','Salon','Growth','Beauty','Hair','Skin','Nail'];return common.includes(word);}
}
