import * as fs from 'fs';
import * as path from 'path';

interface IExtractedKnowledge {
  layoutFamily: { value: string; confidence: number; };
  visualLanguage: { style: string; energy: string; tone: string; industry: string; };
  composition: { primaryFocus: string; secondaryFocus: string; readingFlow: string; balance: string; negativeSpace: string; };
  typography: { headlineStyle: string; hierarchy: string; tracking: string; lineBreakStrategy: string; contrast: string; };
  decorations: Array<{ type: string; purpose: string; emotion: string; }>;
  designRules: string[];
}

function countFrequencies(items: string[]): { [key: string]: number } {
  const counts: { [key: string]: number } = {};
  for (const item of items) {
    const key = item.toLowerCase().trim();
    counts[key] = (counts[key] || 0) + 1;
  }
  return counts;
}

function formatStats(counts: { [key: string]: number }, total: number): string {
  const sorted = Object.entries(counts).sort((a, b) => b[1] - a[1]);
  return sorted.map(([key, count]) => {
    const percentage = ((count / total) * 100).toFixed(1);
    return `- **${key}**: ${percentage}% (${count})`;
  }).join('\n');
}

async function run() {
  console.log("Starting Phase 4: Knowledge Miner");

  const inputPath = path.join(__dirname, 'extracted_knowledge_normalized.json');
  const reportPath = path.join(__dirname, '../../../../.gemini/antigravity-ide/brain/b3ce4c5b-3ec1-4ea3-8d95-264a8c169bfb/artifacts/design_knowledge_graph_report.md');

  if (!fs.existsSync(inputPath)) {
    console.error("extracted_knowledge.json not found! Run the extraction script first.");
    return;
  }

  const results: { hash: string, knowledge: IExtractedKnowledge }[] = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
  const total = results.length;

  if (total === 0) {
    console.error("No knowledge found in the JSON file.");
    return;
  }

  console.log(`Mining intelligence from ${total} layouts...`);

  const layoutFamilies = results.map(r => r.knowledge.layoutFamily.value);
  const visualStyles = results.map(r => r.knowledge.visualLanguage.style);
  const readingFlows = results.map(r => r.knowledge.composition.readingFlow);
  const negativeSpaces = results.map(r => r.knowledge.composition.negativeSpace);
  const headlineStyles = results.map(r => r.knowledge.typography.headlineStyle);
  
  let decorations: string[] = [];
  results.forEach(r => {
    if (r.knowledge.decorations) {
      decorations.push(...r.knowledge.decorations.map(d => d.type));
    }
  });

  const markdown = `# Design Knowledge Graph Report

This report was procedurally generated by the AI Growth Studio Knowledge Miner. It represents the mathematical analysis of **${total} unique professional Canva layouts**. 

Instead of guessing what templates look like, the system has aggregated the actual design psychology used by professional designers.

## 1. Procedural Layout Families
These are the dominant layout architectures discovered across the dataset. The future compiler will only need to know how to build these specific families.

${formatStats(countFrequencies(layoutFamilies), total)}

## 2. Visual Style Systems
The overarching stylistic themes that dictate the mood of the templates.

${formatStats(countFrequencies(visualStyles), total)}

## 3. Composition & Psychology

### Reading Flow Strategies
How the designer forces the human eye to move across the canvas.
${formatStats(countFrequencies(readingFlows), total)}

### Negative Space Allocation
How much breathing room is given around the primary subjects.
${formatStats(countFrequencies(negativeSpaces), total)}

## 4. Typography Systems
The dominant font pairing choices for headlines.

${formatStats(countFrequencies(headlineStyles), total)}

## 5. Decoration Components
The most common geometric primitives used to enhance the layouts.

${formatStats(countFrequencies(decorations), decorations.length)}

---
> [!TIP]
> **What this means for development:** We do not need to build a rigid compiler that tries to handle infinite edge cases. We only need to write a deterministic compiler that can generate the top 5 Layout Families (e.g., Editorial, Minimalist Quote), applying the dominant Reading Flows and Negative Space rules.
`;

  // We are assuming the artifacts directory exists based on the path
  const dir = path.dirname(reportPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(reportPath, markdown, 'utf8');
  console.log(`\nKnowledge Graph Report generated successfully!`);
  console.log(`Saved to: ${reportPath}`);
}

run().catch(console.error);
