/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsentIdRouteImport } from './routes/consent.$id'
import { Route as BrandOnboardingRouteImport } from './routes/brand.onboarding'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentIdRoute = ConsentIdRouteImport.update({
  id: '/consent/$id',
  path: '/consent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandOnboardingRoute = BrandOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => BrandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/brand': typeof BrandRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/content': typeof ContentRoute
  '/generate': typeof GenerateRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/consent/$id': typeof ConsentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/brand': typeof BrandRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/content': typeof ContentRoute
  '/generate': typeof GenerateRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/consent/$id': typeof ConsentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/brand': typeof BrandRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/content': typeof ContentRoute
  '/generate': typeof GenerateRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/consent/$id': typeof ConsentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/auth'
    | '/bookings'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/content'
    | '/generate'
    | '/landing'
    | '/login'
    | '/plans'
    | '/profile'
    | '/signup'
    | '/templates'
    | '/brand/onboarding'
    | '/consent/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/auth'
    | '/bookings'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/content'
    | '/generate'
    | '/landing'
    | '/login'
    | '/plans'
    | '/profile'
    | '/signup'
    | '/templates'
    | '/brand/onboarding'
    | '/consent/$id'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/auth'
    | '/bookings'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/content'
    | '/generate'
    | '/landing'
    | '/login'
    | '/plans'
    | '/profile'
    | '/signup'
    | '/templates'
    | '/brand/onboarding'
    | '/consent/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  BrandRoute: typeof BrandRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CampaignsRoute: typeof CampaignsRoute
  ContentRoute: typeof ContentRoute
  GenerateRoute: typeof GenerateRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  TemplatesRoute: typeof TemplatesRoute
  ConsentIdRoute: typeof ConsentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent/$id': {
      id: '/consent/$id'
      path: '/consent/$id'
      fullPath: '/consent/$id'
      preLoaderRoute: typeof ConsentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/onboarding': {
      id: '/brand/onboarding'
      path: '/onboarding'
      fullPath: '/brand/onboarding'
      preLoaderRoute: typeof BrandOnboardingRouteImport
      parentRoute: typeof BrandRoute
    }
  }
}

interface BrandRouteChildren {
  BrandOnboardingRoute: typeof BrandOnboardingRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandOnboardingRoute: BrandOnboardingRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  BrandRoute: BrandRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CampaignsRoute: CampaignsRoute,
  ContentRoute: ContentRoute,
  GenerateRoute: GenerateRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  TemplatesRoute: TemplatesRoute,
  ConsentIdRoute: ConsentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
