/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsentIdRouteImport } from './routes/consent.$id'
import { Route as BrandOnboardingRouteImport } from './routes/brand.onboarding'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentIdRoute = ConsentIdRouteImport.update({
  id: '/consent/$id',
  path: '/consent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandOnboardingRoute = BrandOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => BrandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/content': typeof ContentRoute
  '/generate': typeof GenerateRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/consent/$id': typeof ConsentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/content': typeof ContentRoute
  '/generate': typeof GenerateRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/consent/$id': typeof ConsentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/content': typeof ContentRoute
  '/generate': typeof GenerateRoute
  '/profile': typeof ProfileRoute
  '/templates': typeof TemplatesRoute
  '/brand/onboarding': typeof BrandOnboardingRoute
  '/consent/$id': typeof ConsentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/auth'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/content'
    | '/generate'
    | '/profile'
    | '/templates'
    | '/brand/onboarding'
    | '/consent/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/auth'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/content'
    | '/generate'
    | '/profile'
    | '/templates'
    | '/brand/onboarding'
    | '/consent/$id'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/auth'
    | '/brand'
    | '/calendar'
    | '/campaigns'
    | '/content'
    | '/generate'
    | '/profile'
    | '/templates'
    | '/brand/onboarding'
    | '/consent/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  BrandRoute: typeof BrandRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CampaignsRoute: typeof CampaignsRoute
  ContentRoute: typeof ContentRoute
  GenerateRoute: typeof GenerateRoute
  ProfileRoute: typeof ProfileRoute
  TemplatesRoute: typeof TemplatesRoute
  ConsentIdRoute: typeof ConsentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent/$id': {
      id: '/consent/$id'
      path: '/consent/$id'
      fullPath: '/consent/$id'
      preLoaderRoute: typeof ConsentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/onboarding': {
      id: '/brand/onboarding'
      path: '/onboarding'
      fullPath: '/brand/onboarding'
      preLoaderRoute: typeof BrandOnboardingRouteImport
      parentRoute: typeof BrandRoute
    }
  }
}

interface BrandRouteChildren {
  BrandOnboardingRoute: typeof BrandOnboardingRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandOnboardingRoute: BrandOnboardingRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  BrandRoute: BrandRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CampaignsRoute: CampaignsRoute,
  ContentRoute: ContentRoute,
  GenerateRoute: GenerateRoute,
  ProfileRoute: ProfileRoute,
  TemplatesRoute: TemplatesRoute,
  ConsentIdRoute: ConsentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
